### ISSUE TITLE
Apply changes failing on operational data store update

### ISSUE THREAD

**Issue by chaichairiko** [sysrepo/sysrepo-python#7]
Hi,
I'm not sure if this is an issue in my implementation, sysrepo-python or sysrepo:
I am trying to update the operational data store. This is the element I am trying to update:
```
list loadbalancer {
    ....
    list nodes {
        .....
        leaf reachability {
            config false;
            type enumeration {
                enum reachable;
                enum unreachable;
            }
        }
        }
```
I have a config that I am reading:
```
(Pdb) sess.get_data(f'/loadbalancer:loadbalancer[name="{self.lb_name}"]')
{'loadbalancer': [{'name': 'scenario_1', 'nodes': [{'ip': '100.0.0.10', 'operation_mode': {'vni': 11002, 'vxlan': None}, 'reachability': 'unreachable', 'actual_state': 'inactive', 'id': 10}]}]}
```

Now, I am trying to **set_item**:
```
 sess.set_item(f'/loadbalancer:loadbalancer[name="scenario_1"]/nodes[ip="100.0.0.10"]/reachability', "reachable")
sess.apply_changes()
```

This is the exception I get:
```
ERROR:sysrepo:Internal error (/opt/dev/sysrepo/src/edit_diff.c:2083).
ERROR:sysrepo:Applying operation "create" failed.
```

Now, looking at the docs, I see that ***set_item*** is only meant for creating, so I've tried ***batch_edit**, but the result is the same.

I have added logs to sysrepo to understand why the operation is "create":
```
WARNING:sysrepo:********************* ATTR_NAME=operation *****************
WARNING:sysrepo:********************* MODULE_NAME=ietf-netconf *****************
WARNING:sysrepo:********************* OP_STR=create *****************
WARNING:sysrepo:********************* OP_INT=8 *****************
WARNING:sysrepo:********************* ATTR_NAME=operation *****************
WARNING:sysrepo:********************* MODULE_NAME=ietf-netconf *****************
WARNING:sysrepo:********************* OP_STR=create *****************
WARNING:sysrepo:********************* OP_INT=8 *****************
WARNING:sysrepo:********************* ATTR_NAME=operation *****************
WARNING:sysrepo:********************* MODULE_NAME=ietf-netconf *****************
WARNING:sysrepo:********************* OP_STR=create *****************
WARNING:sysrepo:********************* OP_INT=8 *****************
```
The logs are added here:
https://github.com/chaichairiko/sysrepo/blob/master/src/edit_diff.c

In the relevant area of the exception

**Comment by rjarry** [comment]
Hi @chaichairiko 

I never tested "pushing" operational data but I read that there are some tricks. Could you share the code with which you are having a problem?

**Comment by chaichairiko** [comment]
@rjarry  you replied so fast I haven't finished to write :D

**Comment by rjarry** [comment]
The session is created with the `"operational"` datastore right?

@michalvasko maybe you can shine some light on this. I am not sure I understand why "create and replace operations are not valid"  https://github.com/sysrepo/sysrepo/blob/v1.4.70/src/edit_diff.c#L2082

**Comment by chaichairiko** [comment]
@rjarry yes, I have changed the datastore beforehand:
`sess.switch_datastore('operational')`

**Comment by michalvasko** [comment]
Hi,
push `operational` changes have a nice API (the same as any other edits) but they are much more complex internally. If you could provide a standalone application (even in Python should be fine) to reproduce this problem, I should be able to fix this somehow.

Generally, there are 2 possibilities. Either there is something wrong happening internally resulting in this invalid operation. Or, the situation is valid (I just could not think of a use-case when writing the code) and it just needs to be properly handled. I am not able to tell which without knowing what is happening internally and to see that, I need to try the use-case locally.

**Comment by chaichairiko** [comment]
Hi,
I've attached a dir with a standalone application that includes the python callback, Dockerfile, xml, yang_model etc.
[sysrepo_test.zip](https://github.com/sysrepo/sysrepo-python/files/5136141/sysrepo_test.zip)

**Comment by rjarry** [comment]
@chaichairiko out of curiosity, did you test with the latest version of the python bindings (0.2.0) as well ?

**Comment by chaichairiko** [comment]
@rjarry We didnt have the chance since our code was already implemented

**Comment by chaichairiko** [comment]
@rjarry , just tried it with sysrepo 0.3.0 that youve just pushed - same issue

**Comment by michalvasko** [comment]
Hi,
sorry it took some time, I was busy with other work. Thanks for the nice example and with that I could reproduce the problem and add it into (C) tests. There was a non-handled situation in some other code part that the internal error you saw. It should be fixed in https://github.com/sysrepo/sysrepo/commit/a2c780ca1bccdd816dc95550a763cc619f8b7025.

Your use-case is a really complex one (storing push operational data in a change callback) and I was not sure it can even be supported first. But I found no reason why it should be forbidden so you should be okay.

**Comment by rjarry** [comment]
Thanks @michalvasko :+1:

**Comment by chaichairiko** [comment]
Thanks @michalvasko !
Can I ask why is it a complex use case? Maybe I a can also optimize my code. 
The app that I showed you isnt the exact use case that I have, but it does show the same issue. My exact use case, is a background task (an asyncio task thats part of the application that runs the callback as well) that once in a while changes operational data (in this case the reachability of a node).
Since operational data can change throughout the application,  I would think that its the way to go, but Im just getting the hang of sysrepo (:

**Comment by michalvasko** [comment]
Like I said, you should be fine using it this way. But, in general, changing *operational* data (the state of any application) directly based on a configuration change seems odd. What I would expect is that the configuration changes, which causes the application to reconfigure itself and perhaps change its state. That will, in effect, cause the *operational* (state) data of the application to change. And that would be seen when these data would be requested because an *operational* callback of the application would be called. Meaning I would expect these data to use the pull *operational* subscription instead of push.

*sysrepo* offers quite a lot of options, which is especially true for *operational* subscriptions so I understand it may often be quite difficult to choose the right one. It all depends on the exact use-case, the goal was to allow as many of them as possible so you can select the most straightforward one.

**Comment by chaichairiko** [comment]
@michalvasko thank you for the very clear explanation.  The way asyncio allows you to run tasks it still runs in the context of the module change, although I could have sent a pull change.  Since you fixed the issue I will leave it like that, but its good to understand how I can do it differently.

**Comment by rjarry** [comment]
@chaichairiko is your problem fixed? Can we close this issue? :)

**Comment by chaichairiko** [comment]
@rjarry yes sir!
