### ISSUE TITLE
Usage of Python Subscribe Callbacks - Accept/Reject and getting the full Config

### ISSUE THREAD

**Issue by esend7881** [sysrepo/sysrepo-python#9]
## Issue

Inside a module subscription function, how can I extract the full config as a single object in a subscribe loop after an `edit-config` atomically?

Also, how can I accept/reject the configs using return values or raised exceptions in the subscription callbacks? 

## Details

Previously in my work, I was using the SWIG based Python API to sysrepo, but it lacks a feature that this API has, namely the use of JSONs in extracting data from sysrepo. It lead me to experiment with your newer module. I am basing my work off of the [examples/application_asyncio.py](https://github.com/sysrepo/sysrepo/blob/v1.4.70/bindings/python/examples/python_application_changes_example.py#L72) file. (FYI: the SWIG file that I used to base my [examples on is here](https://github.com/sysrepo/sysrepo/blob/v1.4.70/bindings/python/examples/python_application_changes_example.py#L72).)

The `changes` object is a list of all the changes, line by line, some are in a JSON format, others are not. 
```
async def module_change_cb(event, req_id, changes, private_data):
    print()
    print("========================")
    print("Module changed event: %s (request ID %s)" % (event, req_id))
    print("----- changes -----")
    for c in changes:
        print(repr(c))
    print("----- end of changes -----")
    print()
    await asyncio.sleep(0)
```
I am wondering if there is a way to have the full edit-config change come in as a single JSON object. Specifically, I am interested in the exact contents of the `edit-config`, both what has change and not changed. 

Here is an example of the output:
```
ChangeCreated(/rmbn-full:RMBN/PacketOperationConf/RuleID[flow-id='4']/action[order='0']: {'order': 0, 'set-dl-dst-action': {'address': '00:00:00:aa:00:54'}})
ChangeCreated(/rmbn-full:RMBN/PacketOperationConf/RuleID[flow-id='4']/action[order='0']/order: 0)
ChangeCreated(/rmbn-full:RMBN/PacketOperationConf/RuleID[flow-id='4']/action[order='0']/set-dl-dst-action: {'address': '00:00:00:aa:00:54'})
ChangeCreated(/rmbn-full:RMBN/PacketOperationConf/RuleID[flow-id='4']/action[order='0']/set-dl-dst-action/address: '00:00:00:aa:00:54')
```
Instead of so many lines with redundant data, the top line actually has the data in JSON form. **I am hoping to instead just get one single line that contains the entire configuration as a single json object.** 

If that is not possible, I noticed I can subscribe to the RPC for `/ietf-netconf:edit-config`

```
sess.subscribe_rpc_call("/ietf-netconf:edit-config", edit_config_rpc, asyncio_register=True)
...
misc_count = 1
async def edit_config_rpc(xpath, input_params, event, private_data):
    pydevd.settrace(suspend=False, trace_only_current_thread=True)
    global misc_count
    misc_count += 1
    print()
    print("========================")
    print("RPC call: %s" % xpath)
    print("params: %s" % input_params)
    out = {"message": "bye bye"}
    print("returning %s" % out)
    print("---------------")
    print()
    if misc_count % 2 == 0:
        print("rejecting!")
        return []
    else:
        print("accepting")
        return None

```
Results in:
```
RPC call: /ietf-netconf:edit-config
params: {'target': {'running': None}, 'default-operation': 'replace', 'test-option': 'test-then-set', 'error-option': 'stop-on-error'}
returning {'message': 'bye bye'}
---------------
```

- Although it does capture the `rpc edit-config` event, I'm not able to see the actual data that is the config. 
  -  Unless there is another path besides `/ietf-netconf:edit-config` or if I need to implement an RPC in my own yang model, it's not clear how to get the full config from within that callback. 
- Also, there doesn't appear to be a way to have the `edit_config_cb` return a value that prompts sysrepo to accept or reject the config. 
  - I.e., similar to `sr.SR_ERR_OK`  or `SR_EV_ABORT`, I need a way to accept or reject a config if its good or bad.

## Environment:

- sysrepo 1.4.70
  - compiled with `cmake -DGEN_LANGUAGE_BINDINGS=ON ..`
- sysrepo-python 0.3.1
- netopeer2 1.1.39 
  - compiled with `cmake -DSYSREPO_TIMEOUT=119 -DRPC_TIMEOUT=120 ..`
- libyang 1.0.184 
  - compiled with `cmake -DGEN_LANGUAGE_BINDINGS=ON ..`
- CentOS 7
- python 2.7.5/3.6.8

## FYI

I originally asked this question in the [sysrepo repo](https://github.com/sysrepo/sysrepo/issues/2139), but was advised to put that question here.

**Comment by rjarry** [comment]
Hi Erik,

> Inside a module subscription function, how can I extract the full config as a single object in a subscribe loop after an edit-config atomically?

Due to performance issues, the full config dictionary is no longer passed as an argument of module change callbacks. See commit https://github.com/sysrepo/sysrepo-python/commit/7118d2e6ceb405e1fd4e42a083b4e77c9b034be8 for detailed explanations.

That said, the [update_config_cache](https://github.com/sysrepo/sysrepo-python/blob/v0.3.1/sysrepo/change.py#L183) function was added as a convenience to maintain a local cache of the "running" config in your application. See [unit tests](https://github.com/sysrepo/sysrepo-python/blob/v0.3.1/tests/test_subs_module_change.py#L47) for examples of use.

Be careful, depending on the `event` argument passed to module change callbacks, the `changes` argument may represent "candidate" changes (i.e. not yet applied into the "running" datastore). If you maintain a local cache of the full "running" configuration, only update that cache when `event == "done"`. If you want a full view of the "candidate" configuration, you need to make a copy of your "running" cached configuration and call `update_config_cache` on that copy. I hope this makes sense.

> Also, how can I accept/reject the configs using return values or raised exceptions in the subscription callbacks?

To reject the configuration, your module change callback should raise a `sysrepo.SysrepoValidationFailedError`. Please note that rejecting the configuration in module change callbacks is only possible when `event == "change"` or `event == "update"`.

This behaviour is described in the docstring of the callback itself:

https://github.com/sysrepo/sysrepo-python/blob/v0.3.1/sysrepo/session.py#L156-L161

> If that is not possible, I noticed I can subscribe to the RPC for /ietf-netconf:edit-config

That is not the correct way of rejecting "candidate" configuration. Only the netconf server (netopeer2 I assume) should subscribe to this RPC. I believe you *can* subscribe to it but you risk interfering with the netconf server and it will not affect the actual sysrepo datastore (which can only be modified via `SysrepoSession` [edit functions](https://github.com/sysrepo/sysrepo-python/blob/v0.3.1/sysrepo/session.py#L722-L910)).

**Comment by esend7881** [comment]
Thank you for the detailed reply. I'll mark this closed and dig in when I can. I just recently had a success with the SWIG API (though by subscribing to the `/ietf-netconf:edit-config` RPC. In my testing so far, I haven't seen any instability from netopeer2 so far.
